# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.21.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o builds/krpg &&  \
        GOOS=windows GOARCH=amd64 go build -o builds/krpg.exe

    - name: Upload Go results
      uses: actions/upload-artifact@v4
      with:
        name: builds
        path: builds/
